#!/usr/bin/env bash
# script to install nginx on your web-01 server
sudo apt-get update -y
sudo apt-get install nginx -y

# Configure Nginx to listen on port 80
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        echo "Holberton School for the win!";
    }
}
EOF'

# Restart Nginx without using systemctl
sudo kill -s HUP $(cat /var/run/nginx.pid)

# Display confirmation message
echo "Nginx installed and configured successfully!"
